name: On commit on main branch

on:
  push:
    branches:
      - main

jobs:
  check-typescript-code:
    name: Check typescript code
    uses: gueriboutmathieu/typescript_utils/.github/workflows/callable__check_typescript_code.yaml@main
    secrets: inherit

  build-and-release:
    name: Build and release
    uses: gueriboutmathieu/typescript_utils/.github/workflows/callable__build_and_release.yaml@main
    needs: check-typescript-code
    secrets: inherit
    with:
      deploy-to-github-pages: true
      custom-domain-name: "gueriboutmathieu.com"
      env-vars: '{"NUXT_PUBLIC_OPENAI_MODEL": "gpt-4.1-nano"}'
      secret-env-vars: '{"NUXT_PUBLIC_API_BASE_URL": "API_BASE_URL", "NUXT_PUBLIC_API_PUBLIC_KEY": "API_PUBLIC_KEY"}'
