name: On commit on PR

on: pull_request

jobs:
  check-typescript-code:
    name: Check typescript code
    uses: gueriboutmathieu/typescript_utils/.github/workflows/callable__check_typescript_code.yaml@main
    secrets: inherit
